# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(ci)'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Wait 5 days before updating, to help circumvent supply chain attacks
    cooldown:
      default-days: 5
      # Exclude plugin-e2e, which is released alongside Grafana itself
      exclude:
        - '@grafana/plugin-e2e'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      unit-test:
        patterns:
          - '@testing-library/*'
          - 'jest*'
          - '@types/jest'
      eslint:
        patterns:
          - '@grafana/eslint-config'
          - 'eslint*'
          - '@typescript-eslint/*'
          - '@stylistic/*'
      grafana:
        patterns:
          - '@grafana/*'
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
        update-types:
          - 'minor'
          - 'patch'

  # Maintain dependencies for the Go backend
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
