/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-eslint-config
 */

import { fixupPluginRules } from '@eslint/compat';
import { defineConfig } from 'eslint/config';
import grafanaConfig from '@grafana/eslint-config';

// eslint-plugin-react still relies on context APIs removed in ESLint 10
// (e.g. `context.getFilename()`), so wrap it with the compat shims.
const withFixedReactPlugin = (config) =>
  config.plugins?.react
    ? { ...config, plugins: { ...config.plugins, react: fixupPluginRules(config.plugins.react) } }
    : config;

export default defineConfig([
  ...grafanaConfig.map(withFixedReactPlugin),
  {
    rules: {
      'react/prop-types': 'off',
    },
  },
  {
    files: ['src/**/*.{ts,tsx}'],

    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
      },
    },

    rules: {
      '@typescript-eslint/no-deprecated': 'warn',
    },
  },
  {
    files: ['./tests/**/*'],

    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
]);
