name: Latest Grafana API compatibility check

on:
  - pull_request

permissions:
  contents: read

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@is-compatible/v1.0.4
        with:
          module: ./src/module.ts
          comment-pr: 'no'
          fail-if-incompatible: 'yes'
